name: Notify Discord on Push

on:
  push:
    branches:
      - "**"  # Listen to pushes on all branches

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build message
        id: msg
        run: |
          REPO="${{ github.repository }}"
          BRANCH="${GITHUB_REF##*/}"
          AUTHOR="${{ github.actor }}"
          COMMITS_URL="https://github.com/${REPO}/commits/${BRANCH}"
          MSG="**${REPO}** pushed to **${BRANCH}** by **${AUTHOR}**\n${COMMITS_URL}"
          echo "text=$MSG" >> $GITHUB_OUTPUT

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TEXT: ${{ steps.msg.outputs.text }}
        run: |
          curl -sS -H "Content-Type: application/json" -X POST \
            -d "{\"content\": \"${TEXT//\"/\\\"}\"}" \
            "$DISCORD_WEBHOOK"
