name: Notify Discord on Push

on:
  push:
    branches:
      - "**"  # Listen to pushes on all branches

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build message
        id: msg
        run: |
          REPO="${{ github.repository }}"
          BRANCH="${GITHUB_REF##*/}"
          AUTHOR="${{ github.actor }}"
          COMMITS_URL="https://github.com/${REPO}/commits/${BRANCH}"

          # Extract info about the latest commit
          LATEST_SHA=$(echo "${{ github.event.head_commit.id }}" | cut -c1-7)
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"

          MSG="**${REPO}** pushed to **${BRANCH}** by **${AUTHOR}**\n"
          MSG+="**Commit:** [${LATEST_SHA}](${COMMIT_URL})\n"
          MSG+="**Author:** ${COMMIT_AUTHOR}\n"
          MSG+="**Message:** ${COMMIT_MSG}\n"
          MSG+="\n<${COMMITS_URL}>"

          echo "text=$MSG" >> $GITHUB_OUTPUT

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TEXT: ${{ steps.msg.outputs.text }}
        run: |
          # Escape quotes properly for JSON
          ESCAPED_TEXT=$(echo "$TEXT" | jq -Rs .)
          curl -sS -H "Content-Type: application/json" -X POST \
            -d "{\"content\": ${ESCAPED_TEXT}}" \
            "$DISCORD_WEBHOOK"
