name: Notify Discord on Push
on:
  push:
    branches: ["**"]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build embed payload
        id: payload
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          PUSHER: ${{ github.actor }}
          COMMIT_ID: ${{ github.event.head_commit.id }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          SHORT_SHA="${COMMIT_ID::7}"
          COMMITS_URL="https://github.com/${REPO}/commits/${BRANCH}"

          payload=$(jq -n \
            --arg repo "$REPO" \
            --arg branch "$BRANCH" \
            --arg pusher "$PUSHER" \
            --arg sha "$SHORT_SHA" \
            --arg curl "$COMMIT_URL" \
            --arg author "$COMMIT_AUTHOR" \
            --arg msg "$COMMIT_MSG" \
            --arg commits "$COMMITS_URL" \
            '{
              embeds: [{
                title: "\($repo) pushed to \($branch)",
                url: $commits,
                description: $msg,
                color: 5793266,
                fields: [
                  { name: "Commit", value: "[\($sha)](\($curl))", inline: true },
                  { name: "Author", value: $author, inline: true },
                  { name: "Pusher", value: $pusher, inline: true }
                ],
                timestamp: (now | todateiso8601)
              }]
            }')

          echo "json=$payload" >> "$GITHUB_OUTPUT"

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          JSON: ${{ steps.payload.outputs.json }}
        run: |
          curl -sS -H "Content-Type: application/json" -X POST -d "$JSON" "$DISCORD_WEBHOOK"
