name: Notify Discord on Push
on:
  push:
    branches: ["**"]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build message
        id: msg
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          PUSHER: ${{ github.actor }}
          COMMIT_ID: ${{ github.event.head_commit.id }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          COMMITS_URL="https://github.com/${REPO}/commits/${BRANCH}"
          SHORT_SHA="${COMMIT_ID::7}"

          # Build with real newlines so Discord doesn't show "\n"
          printf -v MSG '**%s** pushed to **%s** by **%s**\n' "$REPO" "$BRANCH" "$PUSHER"
          printf -v MSG '%s**Commit:** [%s](%s)\n' "$MSG" "$SHORT_SHA" "$COMMIT_URL"
          printf -v MSG '%s**Author:** %s\n' "$MSG" "$COMMIT_AUTHOR"
          printf -v MSG '%s**Message:** %s\n\n' "$MSG" "$COMMIT_MSG"
          printf -v MSG '%s<%s>\n' "$MSG" "$COMMITS_URL"

          {
            echo 'text<<EOF'
            echo "$MSG"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TEXT: ${{ steps.msg.outputs.text }}
        run: |
          payload=$(jq -n --arg content "$TEXT" '{content: $content}')
          curl -sS -H "Content-Type: application/json" -X POST -d "$payload" "$DISCORD_WEBHOOK"
